export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
export const SHOW_PRODUCTS_IN_CART = 'SHOW_PRODUCTS_IN_CART';
export const HIDE_PRODUCTS_IN_CART = 'HIDE_PRODUCTS_IN_CART';

